feeds/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView
from django.http import HttpResponse

from .views import KeyFeed, CookieFeed, Homepage
from .models import TestFeedItem


urlpatterns = patterns('',
                       url('^$', Homepage.as_view(template_name="index.html" )),
                       url(r'^robots\.txt$',
                           lambda r: HttpResponse("User-agent: *\nDisallow: /feed/*\nDisallow: /item/*",
                                                  mimetype="text/plain")),
                       url('^item/(?P<id>\d+)', DetailView.as_view(pk_url_kwarg="id", model=TestFeedItem), name="view"),
                       url('^feed/(?P<feed_type>(rss|atom))/cookie', CookieFeed(), name="cookie"),
                       url('^feed/(?P<feed_type>(rss|atom))/(?P<key>\S+)$', KeyFeed(), name="key"),
                       )

feedtester/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url('^', include('feeds.urls', namespace="feeds")),
)

feeds/models.py
from django.db import models
from django.contrib.webdesign import lorem_ipsum
from django.core.urlresolvers import reverse


class TestFeed(models.Model):
    key = models.TextField(primary_key=True)
    created = models.DateField(auto_now_add=True)


class TestFeedItem(models.Model):
    feed = models.ForeignKey(TestFeed, related_name="items")
    created = models.DateTimeField(auto_now_add=True)
    display_time = models.DateTimeField(auto_now_add=True)
    title = models.TextField(default=lorem_ipsum.sentence)
    content = models.TextField(default=lambda: "\n".join(lorem_ipsum.paragraphs(2)))

    def get_absolute_url(self):
        return reverse("feeds:view", args=[self.id])

    class Meta:
        get_latest_by = "created"

feeds/views.py
from __future__ import division

import uuid
import datetime
import random

from django.contrib.syndication.views import Feed
from django.views.generic import TemplateView
from django.utils.feedgenerator import Atom1Feed, Rss201rev2Feed
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
import string
from .models import TestFeed, TestFeedItem


class ScrewedUpResponse(HttpResponse):
    def items(self):
        return [("lol\n\n!", "o\n\br\0")]  # Send an invalid header to the client. Messes stuff up


class Homepage(TemplateView):
    def get_context_data(self, **kwargs):
        ctx = super(Homepage, self).get_context_data(**kwargs)
        ctx.update({"uuid": uuid.uuid4})
        return ctx


class BaseFeed(Feed):
    title = "A feed"
    description = "A feed description"

    def __call__(self, request, *args, **kwargs):
        self.feed_type_name = kwargs["feed_type"]
        self.feed_type = Rss201rev2Feed if self.feed_type_name == "rss" else Atom1Feed
        self.simulate_issue = None

        if random.randint(0, 100) > 75 and "tryme" in request.GET:
            self.simulate_issue = random.choice(["500", "redirect", "non_xml",
                                                 "invalid_xml", "non_http",
                                                 "screwed_results", "future_dates"])

            if self.simulate_issue == "500":
                return HttpResponse("500 internal server error", status=500)
            elif self.simulate_issue == "redirect":
                return HttpResponseRedirect("http://google.com")
            elif self.simulate_issue == "non_xml":
                return HttpResponse("This is some non-xml content for you", content_type="text/plain")

        result = super(BaseFeed, self).__call__(request, *args, **kwargs)

        if self.simulate_issue == "invalid_xml":
            # Replace a bunch of characters in the response text
            resp_length = len(result.content)
            content = list(result.content)
            for i in xrange(int(resp_length / 10)):
                idx_to_change = random.randint(0, resp_length)
                content[idx_to_change] = random.choice(string.printable)

            result.content = "".join(content)
        elif self.simulate_issue == "non_http":
            return ScrewedUpResponse()

        return result

    def get_key(self, request, *args, **kwargs):
        raise NotImplementedError()

    def get_total_seconds(self, elapsed):
        return (elapsed.microseconds + (elapsed.seconds + elapsed.days*24*3600) * 1e6) / 1e6  # Python 2.6 compatability

    def get_object(self, request, *args, **kwargs):
        key = self.get_key(request, *args, **kwargs)
        obj, created = TestFeed.objects.get_or_create(key=key)

        if created:
            last_item = TestFeedItem.objects.create(feed=obj)
        else:
            last_item = obj.items.latest()

        trigger_time = kwargs.get("time", "30")

        create_trigger = min(max(int(trigger_time if trigger_time.isdigit() else "30"), 15), 60)

        # Work out how long it has been since we have created a post
        created_ago = (datetime.datetime.now() - last_item.created)

        if created_ago > datetime.timedelta(seconds=create_trigger):
            # Create a new item with a time between
            random_time = created_ago + datetime.timedelta(seconds=random.randint(1, int(self.get_total_seconds(created_ago))))
            TestFeedItem.objects.create(feed=obj, display_time=random_time)

        return obj

    def items(self, obj):
        items = obj.items
        if self.simulate_issue == "screwed_results":
            return items.order_by("?")[:10]

        return items.order_by("-created")[:10]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.content

    def item_link(self, item):
        return item.get_absolute_url()

    def item_guid(self, item):
        return str(item.id)

    def item_pubdate(self, item):
        if self.simulate_issue == "future_dates":
            if random.randint(1, 2) == 2:
                return datetime.datetime.now() + datetime.timedelta(minutes=random.randint(0, 60))
        return item.display_time

    def link(self, obj):
        return reverse("feeds:key", args=[self.feed_type_name, obj.key])


class CookieFeed(BaseFeed):
    def get_key(self, request, *args, **kwargs):
        if "feed_id" not in request.session:
            request.session["feed_id"] = uuid.uuid4().hex
        return request.session["feed_id"]


class KeyFeed(BaseFeed):
    def get_key(self, request, *args, **kwargs):
        return kwargs["key"]

templates/feeds/testfeeditem_detail.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

    <h1>{{ object.title }} </h1>
    <p><small>{{ object.created }}</small> </p>
    <p>
        {{ object.content|linebreaksbr }}
    </p>

    <p>Feed: <a href="{% url "feeds:key" "rss" object.feed_id %}">RSS:{{ object.feed_id }}</a> | <a href="{% url "feeds:key" "atom" object.feed_id %}">Atom:{{ object.feed_id }}</a> </p>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Feed creator</title>
</head>
<body>
    <h1>Feed creator</h1>
    <p>
        This is a very simple service that generates persistent updating RSS and ATOM feeds.
    </p>
    <h3>Usage:</h3>
    <p>
        A feed can be accessed by using any string as a key by these formats: {% url 'feeds:key' 'rss' 'KEY' %} or {% url 'feeds:key' 'atom' 'KEY' %}. For example: <a href='{% url 'feeds:key' 'rss' uuid.hex %}'>{% url 'feeds:key' 'rss' uuid.hex %}</a> or <a href='{% url 'feeds:key' 'atom' uuid.hex %}'>{% url 'feeds:key' 'atom' uuid.hex %}</a>
    </p>
    <p>
        If you don't want to specify a key you can request <a href='{% url 'feeds:cookie' 'rss' %}'>{% url 'feeds:cookie' 'rss' %}</a>. This will set a cookie which you will need to keep and re-send with each request.
    </p>
    <h3>Options</h3>
    <h4>Message rate</h4>
    <p>
        By default a new item will be created when the feed is requested, if one hasn't been created in the last 30 seconds. You can pass an integer between 15 and 60 in the time parameter. To create a feed with a new entry every 20 seconds request this URL: <a href='{% url 'feeds:key' 'rss' uuid.hex %}?time=20'>{% url 'feeds:key' 'rss' uuid.hex %}?time=20</a>
    </p>
    <h4>Simulate issues</h4>
    <p>
        Feeling brave? Append ?tryme (e.g <a href='{% url 'feeds:key' 'rss' uuid.hex %}?tryme'>{% url 'feeds:key' 'rss' uuid.hex %}?tryme</a>) to any URL. This will sometimes cause one of the following things to happen:
        <ul>
            <li>Invalid XML</li>
            <li>Internal server error</li>
            <li>Non XML response</li>
            <li>Non HTTP response</li>
            <li>Redirect to another page</li>
            <li>Out of order or missing results</li>
            <li>Results with future dates</li>
        </ul>
    </p>

    <h3>Source?</h3>
    <a href="https://github.com/orf/feedtester">Here on GitHub</a>

    <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48915373-2', 'tomforb.es');
  ga('send', 'pageview');

</script>

</body>
</html>